version: '2'

networks:
  default:
    driver: bridge

services:
  magnis:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    ports: 
      - "80:80"
    networks: 
      - default
    depends_on: 
      - db    
    volumes:
      - "../magnis:/var/www/magnis"
      - "./conf/nginx:/etc/nginx/sites-available"      
  db:
    image: mysql:latest
    networks: 
      - default
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: magnis
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - "./database:/var/lib/mysql"
